# STEP 1
FROM node:16-alpine

WORKDIR /app

COPY . .

RUN npm i 

RUN npm run build


# STEP 2
FROM node:16-alpine
WORKDIR /app
ENV NODE_ENV prod
COPY --from=build /app ./
CMD ["npm","run","start:dev"]